const teamImages = import.meta.glob("./assets/team/webp/*.{jpg,png,webp}", {
  eager: true,
});
const teamMembers = [
  {
    name: "Joana Regadas",
    position: "Presidente",
    imageUrl: "regadas.webp",
    sector: "Presidência",
    curso: "Mestrado em Engenharia Biomédica",
    linkedin: "https://www.linkedin.com/in/joanaregadas/",
  },
  {
    name: "Carolina Alberto",
    position: "Vice-Presidente Adjunta",
    imageUrl: "carolina.webp",
    sector: "Presidência",
    curso: "Mestrado em Engenharia Biomédica",
    linkedin: "",
  },
  {
    name: "Pedro Rocha",
    position: "Tesoureiro",
    imageUrl: "rocha.webp",
    sector: "Presidência",
    curso: "Mestrado em Engenharia de Computadores e Telemática",
    linkedin: "https://www.linkedin.com/in/pedro-lebre-da-rocha/",
  },
  {
    name: "Guilherme Carola",
    position: "Tesoureiro Adjunto",
    imageUrl: "carola.webp", 
    sector: "Presidência",
    curso: "Licenciatura em Administração Pública",
    linkedin: "",
  },
  {
    name: "Hugo Oliveira",
    position: "Secretário Geral",
    imageUrl: "hugo.webp",
    sector: "Presidência",
    curso: "Mestrado em Engenharia Mecânica",
    linkedin:
      "https://www.linkedin.com/in/hugo-oliveira-276aba175?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  },
  {
    name: "Francisco Teixeira",
    position: "Vice-Presidente",
    imageUrl: "kiko.webp",
    sector: "Cultura",
    curso: "Mestrado Integrado em Engenharia Mecânica ",
    linkedin: "https://www.linkedin.com/in/francisco-teixeira-154bbb243",
  },
  {
    name: "André Vieira",
    position: "Vogal",
    imageUrl: "vieira.webp",
    sector: "Cultura",
    curso: "Mestrado em Engenharia Mecânica",
    linkedin: "https://www.linkedin.com/in/andré-vieira-6257472b8",
  },
  {
    name: "Mafalda Ribeiro",
    position: "Vogal",
    imageUrl: "mafalda.webp",
    sector: "Cultura",
    curso: "Licenciatura em Fisioterapia",
    linkedin: "",
  },
  {
    name: "Carolina Correia",
    position: "Vice-Presidente",
    imageUrl: "carol_Correia.webp",
    sector: "Política Educativa",
    curso: "Mestrado em Engenharia e Gestão Industrial",
    linkedin: "https://www.linkedin.com/in/carolinacorreia03",
  },
  {
    name: "Gonçalo Lourenço",
    position: "Vogal",
    imageUrl: "gon_Lourenco.webp",
    sector: "Política Educativa",
    curso: "Licenciatura em Línguas e Relações Empresariais",
    linkedin: "https://www.linkedin.com/in/gonçalo-lourenço-a6185225a",
  },
  {
    name: "Ana Rita Carvalhinho",
    position: "Vogal",
    imageUrl: "ritinha.webp",
    sector: "Política Educativa",
    curso: "Mestrado em Psicologia da Saúde e Neuropsicologia",
    linkedin: "",
  },
  {
    name: "Tomás Oliveira",
    position: "Vice-Presidente",
    imageUrl: "tomas.webp",
    sector: "Desporto e Bem Estar",
    curso: "Mestrado em Engenharia Química",
    linkedin:
      "https://www.linkedin.com/in/tom%C3%A1s-oliveira-265609313?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  },
  {
    name: "Francisco Luís",
    position: "Vogal",
    imageUrl: "chiquinho.webp",
    sector: "Desporto e Bem Estar",
    curso: "Licenciatura em Engenharia Eletrotécnica e Computadores",
    linkedin: "https://www.linkedin.com/in/fdominguesluis",
  },
  {
    name: "Matilde Pilar",
    position: "Vogal",
    imageUrl: "pilar.webp",
    sector: "Desporto e Bem Estar",
    curso: "Mestrado em Engenharia de Materiais ",
    linkedin: "https://www.linkedin.com/in/matilde-pilar-2029b6276/",
  },
  {
    name: "Ana Sofia Delgado",
    position: "Vice-Presidente",
    imageUrl: "sofia.webp",
    sector: "Apoio aos Núcleos",
    curso: "Mestrado em Biomedicina Molecular",
    linkedin: "",
  },
  {
    name: "João Luís",
    position: "Vogal",
    imageUrl: "joao.webp",
    sector: "Apoio aos Núcleos",
    curso: "Mestrado em Cibersegurança",
    linkedin: "",
  },
  {
    name: "Tomás Ferraz",
    position: "Vogal",
    imageUrl: "tferraz.webp",
    sector: "Apoio aos Núcleos",
    curso: "Licenciatura em Administração Pública",
    linkedin: "",
  },
  {
    name: "Luciana Santos",
    position: "Vice-Presidente",
    imageUrl: "luciana.webp",
    sector: "Administração Interna",
    curso: "Lincenciatura em Engenharia Química",
    linkedin: "https://www.linkedin.com/in/lucianasantos01",
  },
  {
    name: "Francisco Domingues",
    position: "Vogal",
    imageUrl: "chico.webp",
    sector: "Administração Interna",
    curso: "Licenciatura em Gestão e Planeamento em Turismo",
    linkedin: "",
  },
  {
    name: "José Abilheira",
    position: "Vogal",
    imageUrl: "abilheira.webp",
    sector: "Administração Interna",
    curso: "Licenciatura em Multimédia e Tecnologias da Comunicação",
    linkedin: "",
  },
  {
    name: "Vasco Carreira",
    position: "Vogal",
    imageUrl: "vasco.webp",
    sector: "Administração Interna",
    curso: "Mestrado em Engenharia Aeroespacial",
    linkedin: "https://www.linkedin.com/in/vasco-carreira-88a25a266/",
  },
  {
    name: "Tiago Coelho",
    position: "Vogal",
    imageUrl: "tiago.webp",
    sector: "Administração Interna",
    curso: "Licenciatura em Engenharia Civil",
    linkedin:
      "https://www.linkedin.com/in/tiago-coelho-69495a297?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app ",
  },
  {
    name: "Beatriz Machado",
    position: "Vice-Presidente",
    imageUrl: "bia.webp",
    sector: "Comunicação e Imagem",
    curso: "Mestrado em Design",
    linkedin: "",
  },
  {
    name: "Tiago Eusébio",
    position: "Vogal",
    imageUrl: "eusebio.webp",
    sector: "Comunicação e Imagem",
    curso: "Mestrado em Engenharia e Design de Produto",
    linkedin: "https://www.linkedin.com/in/tiago-eus%C3%A9bio-4b276b264/",
  },
  {
    name: "Letícia Carvalho",
    position: "Vogal",
    imageUrl: "leticia.webp",
    sector: "Comunicação e Imagem",
    curso: "Licenciatura em Multimédia e Tecnologias da Comunicação",
    linkedin: "",
  },
  {
    name: "Maria Queiroga",
    position: "Vogal",
    imageUrl: "maria_Queiroga.webp",
    sector: "Comunicação e Imagem",
    curso: "Licenciatura em Marketing",
    linkedin: "",
  },
  {
    name: "Joana Ferreira",
    position: "Vice-Presidente",
    imageUrl: "joana_ferreira.webp",
    sector: "Aveiro é Nosso",
    curso:
      "Mestrado em Educação Pré-Escolar e Ensino do 1º Ciclo do Ensino Básico",
    linkedin: "",
  },
  {
    name: "Bruna Costa",
    position: "Vogal",
    imageUrl: "bruna.webp",
    sector: "Aveiro é Nosso",
    curso: "Mestrado em Marketing ",
    linkedin: "https://www.linkedin.com/in/bruna-costa-a61a37201/",
  },
  {
    name: "Larissa Cavalcanti",
    position: "Vogal",
    imageUrl: "larissa.webp",
    sector: "Aveiro é Nosso",
    curso: "Licenciatura em Ciências Biomédicas",
    linkedin: "",
  },
  {
    name: "Inês Filipe",
    position: "Presidente",
    imageUrl: "fifi.webp",
    sector: "Mesa da Assembleia Geral",
    curso: "Mestrado em Ensino de matemática no 3º ciclo e secundário",
    linkedin: "",
  },
  {
    name: "Nânci Marques",
    position: "Vice-Presidente",
    imageUrl: "nanci.webp",
    sector: "Mesa da Assembleia Geral",
    curso: "Mestrado em Engenharia Geológica",
    linkedin: "https://www.linkedin.com/in/n%C3%A2nci-jesus/",
  },
  {
    name: "Francisca Ferreira",
    position: "Secretária",
    imageUrl: "francisca.webp",
    sector: "Mesa da Assembleia Geral",
    curso: "Mestrado em Gestão Comercial",
    linkedin: "https://www.linkedin.com/in/francisca-ferreira-425345268",
  },
  {
    name: "Maria Inês",
    position: "Secretária",
    imageUrl: "maria_Ines.webp",
    sector: "Mesa da Assembleia Geral",
    curso: "Licenciatura em Matemática ",
    linkedin: "",
  },

  {
    name: "Iara Costa",
    position: "Secretária",
    imageUrl: "iara.webp",
    sector: "Mesa da Assembleia Geral",
    curso: "Licenciatura em Biologia",
    linkedin: "",
  },
  {
    name: "Bernardo Ferreira",
    position: "Presidente",
    imageUrl: "bernardo.webp",
    sector: "Conselho Fiscal e de Jurisdição",
    curso: "Programa Doutoral em Bioquímica",
    linkedin: "https://www.linkedin.com/in/bernardo-ferreira-6b86451a3/",
  },
  {
    name: "Mariana Gomes",
    position: "Vice-Presidente",
    imageUrl: "mariana_gomes.webp",
    sector: "Conselho Fiscal e de Jurisdição",
    curso: "Mestrado em Gestão",
    linkedin:
      "https://www.linkedin.com/in/mariana-gomes-955a86252?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    name: "Beatriz Gouveia",
    position: "1.º Secretária",
    imageUrl: "beatriz.webp",
    sector: "Conselho Fiscal e de Jurisdição",
    curso: "Licenciatura em Engenharia do Ambiente",
    linkedin: "",
  },
  {
    name: "Lourenço Mota",
    position: "2° Secretário",
    imageUrl: "lourenco.webp",
    sector: "Conselho Fiscal e de Jurisdição",
    curso: "Licenciatura em Design de Produto e Tecnologia",
    linkedin: "",
  },
  {
    name: "Lara Macieira",
    position: "Relatora",
    imageUrl: "lara.webp",
    sector: "Conselho Fiscal e de Jurisdição",
    curso: "Licenciatura em Contabilidade",
    linkedin: "",
  },
].map((member) => ({
  ...member,
  imageUrl: teamImages[`./assets/team/webp/${member.imageUrl}`]?.default || "",
}));

export { teamImages, teamMembers };
